updated api to include BT project name and data columns. BT Issue #18
OutdoorRD/trails-viz pull request #190
Opened 2023-09-06 23:04 UTC by Laurabraun1

2023-09-07 18:55 UTC, sgwinder requested changes
Thanks Laura! I left a couple of comments, and added @jblehr as a reviewer as well - Jacob I'll leave it up to you to test whether this works locally, and to incorporate any changes to the app required to add the mobile data.

2023-09-07 18:55 UTC, sgwinder commented on trails-viz-api/trailsvizapi/config/app_config.py
> +    'Bridger Teton': 'BT'
I think Bridger-Teton should have a hyphen (here and in general)

2023-09-07 18:55 UTC, sgwinder commented on trails-viz-api/trailsvizapi/config/app_config.py
> +    'BT':['flickr','twitter','alltrails','ebird','onsite']
This will also need to include the name of the mobile data column.

2023-09-07 20:05 UTC, jblehr commented on trails-viz-api/trailsvizapi/config/app_config.py
>      'Coronado': ['estimate', 'flickr', 'twitter', 'alltrails', 'ebird', 'onsite']
The `'Coronado'` line also needs a comma after it if you are adding a new line after (each line should end with a comma).

2023-09-07 20:06 UTC, jblehr commented on trails-viz-api/trailsvizapi/config/app_config.py
>      'Coronado': 'Coronado'
The 'Coronado' line also needs a comma after it if you are adding a new line after (each line should end with a comma).

2023-09-08 02:15 UTC, Laurabraun1 commented
Thanks @jblehr and @sgwinder - as always silly mistakes that shouldn't have happened. All fixed now! I added the mobile column as 'mobile' since I wasn't sure where we landed with gravy vs. mobile.

2023-09-08 16:34 UTC, sgwinder commented
Thanks @Laurabraun1 ! 

As a note for @jblehr - the column in the data file is called `gravy`. I'm not sure whether that needs to match the argument in the `app_config.py` file?

2023-09-08 20:31 UTC, jblehr commented
Noting here that this PR will also close https://github.com/OutdoorRD/trails-viz-data/issues/50.

2023-09-08 23:18 UTC, jblehr approved these changes
Noting here that I changed `app_config.py` to match the column name in the data: "gravy".

2023-09-08 23:18 UTC, merged